# New School Innovation for Old School Industry {#Smart-Paper-Mills}

#### Keywords{-}

paper industry, data analysis, machine learning 

## Need for upgrades{-}

 The US Forest Paper and Packaging Industry is a 4 billion dollar net income industry [@paperindustry]. While many innovations have occurred in the operating technology, progress in the reporting and analytical technology has vastly fallen behind. Many papermakers didn't see the need: Why spend the money on something that isn't going to make the machine run faster, or cause fewer sheet breaks (when the sheet of paper breaks as it is being formed by the machine, causing downtime)? They argued that investment dollars were better spent on new chemicals or new showerhead combinations. However, as technology has gotten cheaper those arguments don’t hold as much sway.

## Technology needs to be brought not just to the present, but to the future{-}

Most mills have the solutions to the best operations within their grasp, they simply don’t know how to access them. One of the first steps to building a data science tool is having good data to analyze, and most modern mills do have extensive data historians. These hold temperatures, tonnage, shift schedules and many other bits and pieces of information that could prove helpful. They also have data visualization software to display this data. And while each program has its own set of analytical tools, they fail to fully bridge the gap between data visualization and data analytics. 

That is where my software suite, SmartMill, could be integrated. As a multi-faceted collection of tools, SmartMill will build upon current data historian and visualization software to add intelligence to the data. Some of the modules that will be included are shift analysis of production metrics, which will identify crews who either need new more training or should be recruited to train their coworkers, and machine learning applications, which will attempt to predict certain types of sheet breaks before they happen. Various parties may already do some of this analysis, but often it is one-off analysis that is based in Excel and hard to adjust, update, or reformat. SmartMill will bring everything to a single place and provide users with the flexibility they need. All of this is done as real time as physically possible. Once the platform is built to quickly do these kinds of analysis projects, new ideas can be tested and added as they become available.  

## Physical impacts with information{-}

Although traditional uses of paper may be decreasing, new demands for paper are popping up in unexpected places, such as urban development and technology packaging [@newpaper]. This is an industry that is here to stay, and it is a huge opportunity market for technology to make significant gains. The shift analysis will lead to a better trained workforce that has the ability to operate the mill more homogenously. The sheet break predictor will allow for changes to be made to mitigate the break before it happens, leading to less downtime and more production. And while the technology exists to create these tools, some challenges do exist to implementation. In addition to the cost in time and money to code and buy technology, there is also the personel component. One of the biggest problems will be convincing mills that the methods they have used for the last 50 years can be drastically improved, and that they should trust the conclusions of the computer. Simply creating some nifty tools will not be enough; we will have to use our extensive industry knowledge and commmunication skills to ensure proper implementation, application, and execution of our product. 
 
   
