# SmartChem - Papermill Chemical Tracking {#smart chemicals}

#### Keywords{-}

paper mill, machine learning, chemical usage reduction{-}

## Why do we need chemicals{-}

When the general public thinks about the composition of paper, most people can come up with the fact that it is made from trees, or that it is recycled from other paper. What is often not thought of is the sheer number of chemicals that also go into making paper to create different paper properties. There are thousands of grades of paper, with different properties that are important to all of them. Some of those properties include strength, tear, porosity, and color. The correct cocktail of chemicals can greatly influence the manifestation of these properties. While general industry knowledge gives mills an idea of where to start, each mill is unique in how fiber is brought to the machine and which specific chemicals are applied to the machine to create the test. However, chemicals are very expensive and can cost a mill hundreds of thousands of dollars a week. That is where my tool, SmartChem, would come in. Using data science, SmartChem will help mills use chemicals more efficiently in the paper production process.

## How can we control them{-}

Using advanced machine learning techniques, SmartChem, a subsidiary of SmartMill, will use our own historical data to create models of the perfect formulation of chemicals needed to meet test properties. It will use chemical flow data as well as other process data (consistency, temperature, pressure, etc.). My tool will save the customer in two ways: 

1. The tool will ensure that enough chemicals are used so that the paper produced meets test requirements and rejects are reduced. 
2. The tool will minimize the amount of chemicals that are being wasted. 

At initialization, SmartChem will require some time to set up, as extensive history must be looked at to create the model. Industry research and knowledge can also be used to make initial assumptions and build in domain expertise. However, the power of this tool is in using machine learning to update the model based upon feedback and changing machine conditions. SmartChem also stands above competition in its ability to customize solutions for each mill site. 

## What are obstacles to optimization{-}

The initial set-up for SmartChem will be a lot of work. We will need to identify all of the potential chemical flows and other contributing factors to paper quality. In addition to identifying and adding all of these variables to the model, there could be instrumentation issues. Paper mills are old, and often not all pipes have flowmeters or other sensors. In order for this product to be successful, the customer will have to be extremely involved in the set-up and implementation so that mill knowledge can be properly leveraged. However, the relationship that is built between SmartChem and the mill site will lead to personalized and sustainable solutions. As the industry shrinks, tools like SmartChem will be the edge for paper mills to remain competitive without capital investment. 

